// Module Imports
const { ipcMain } = require('electron')
const RealSerialPort = require('serialport')
const MockSerialPort = require('./mockSerialPort')
let SerialPort = RealSerialPort
const Readline = require('@serialport/parser-readline')

// Local Imports
const MicroDebugWindow = require('./windows/micro-debug/micro-debug')
const MainWindow = require('./windows/main/main')

let port = null
let ready = false
let configured = false

// Open
// Attempts to open the specified port. Returns resolve if successful
// \param[obj] device - device object (generated by)
function Open(device){
  return new Promise((resolve, reject) => {
    // Close any open port
    if(port){
      console.log('closing the open port')
      port.close((err) => {
        if(err) reject()

        // reset ready and configured
        ready = false
        configured = false

        OpenPort(device).then(() => {
          console.log('closed')
          resolve()
        }).catch(() => {
          console.log('failed to close')
          reject()
        })
      })
    }else{
      OpenPort(device).then(() => {
        resolve()
      }).catch(() => {
        console.log('Catching OpenPort reject')
        reject()
      })
    }
  })
}

function HandleConfig(configObj) {
  if(configObj.baud){
    port.update({
      baudRate: configObj.baud
    })
  }
  if(configObj.settings){
    MainWindow.LoadSettings(configObj)
  }
}

function OpenPort(device){
  return new Promise((resolve, reject) => {
    // Open the port
    port = new SerialPort(device.comName, {
      // no options
    })

    // Attach a newline parser
    const parser = port.pipe(new Readline({ delimiter: '\r\n' }))

    // Handle Incoming Data
    parser.on('data', (data) => {
      // Handle 'READY' keyword
      if(data === 'READY'){
        ready = true
        port.write('CONFIG')
      
      // Handle 'CONFIG' return
      }else if(configured === false && ready === true){
        let config = JSON.parse(data)
        HandleConfig(config)
        configured = true
        resolve()
      }

      else
        MicroDebugWindow.Update(data)
    })

    // Handle open
    port.on('open', () => {
      console.log('Open')
    })

    // Handle error
    port.on('error', () => {
      console.log('Error')
      reject()
    })
  })
}

// Handle serial open
ipcMain.on('serial:open', (e, device) => {
  Open(device).then(() => {
    e.reply('serial:opened', true)
  }).catch(() => {
    console.log('Failed to Open')
  })
})




module.exports = {
  GetDevices: function(){
    return new Promise((resolve, reject) => {
      SerialPort.list().then((ports) =>{
        console.log(ports)
        resolve(ports)
        ports.forEach((port) => {
          console.log("----- Port -----\n", port)
        })
      }, (err) => {
        console.error(err)
      })
    })
  },

  UpdateMockSerial: function(){
    if(process.useMockMicros)
      SerialPort = MockSerialPort
    else
      SerialPort = RealSerialPort
  }
}